apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-2
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: gcr.io/protean-mind-249804/maven-with-actions:1.0
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
